[overrides]
# What difficulty should be replaced by Very Hard.
# When the current difficulty is Very Hard, enemies will have a "+" next to their level.
# Note: if Very Hard is disabled, this setting has no effect.
# One of "easy", "normal", or "hard"
veryhard = "hard"
# What difficulty should be replaced by Custom.
# When the current difficulty is Custom, enemies will have a "-" next to their level.
# Note: if Custom is disabled (it is disabled by default!), this setting has no effect.
# One of "easy", "normal", or "hard"
custom = "easy"

[veryhard]
# Whether the "Very Hard" mode should be enabled
enabled = true 
# Whether enemy health should be updated to the Very Hard setting (200%).
# If this is set to false, enemies will have health values from the overridden
# difficulty.
health = true

# Custom settings. By default, this replaces the Easy difficulty.
[custom]
# Whether custom mode should be enabled
enabled = false
# Enemy damage multiplier.
# [25->250%, increments of 25]
# Easy: 75%, Normal: 100%, Hard: 125%, Very Hard: 125%
enemy-attack-power = 100
# How fast enemies recharge arts.
# [25->250%, increments of 25]
# Easy: 75%, Normal: 100%, Hard: 125%, Very Hard: 125%
enemy-recharge-speed = 100
# Enemy HP multiplier.
# [25->250%, increments of 25]
# Easy: 50%, Normal: 100%, Hard: 150%, Very Hard: 200%
enemy-health = 100
# Multiplier for duration of debuff effects from enemies. 
# [25->250%, increments of 25]
# Easy: 50%, Normal: 100%, Hard: 150%, Very Hard: 200%
enemy-debuff-resist = 100
# Multiplier for the duration of combos. 
# [25->250%, increments of 25]
# Easy: 100%, Normal: 100%, Hard: 75%, Very Hard: 75%
combo-duration = 100
# Chain attack gauge buildup multiplier. 
# [25->250%, increments of 25]
# Easy: 150%, Normal: 100%, Hard: 75%, Very Hard: 50%
chain-attack-buildup = 100
# Talent art gauge buildup multiplier. 
# [25->250%, increments of 25]
# Easy: 100%, Normal: 100%, Hard: 75%, Very Hard: 50%
talent-buildup = 100
# Player healing power multiplier. 
# [25->250%, increments of 25]
# Easy: 100%, Normal: 100%, Hard: 75%, Very Hard: 50%
player-healing = 100
# Multiplier for each chain attack damage ratio increase. 
# [25->250%, increments of 25]
# Easy: 50%, Normal: 100%, Hard: 50%, Very Hard: 50%
chain-damage-ratio = 100
# Special attacks on enrage that cause the chain attack gauge to deplete. 
# [true or false]
# Very Hard: true
rage-strikes = false
# Level buildup speed for interlink. 
# [25->250%, increments of 25]
# Easy: 125%, Normal: 100%, Hard: 75%, Very Hard: 50%
interlink-level-buildup = 100
# Heat buildup speed for interlink.
# [25->250%, increments of 25]
# Easy: 75%, Normal: 100%, Hard: 125%, Very Hard: 125%
interlink-heat-buildup = 100
# (Future Redeemed) Charge speed for Pair specials.
# [25->250%, increments of 25]
# Easy: 100%, Normal: 100%, Hard: 75%, Very Hard: 50%
dlc4-pair-special-buildup = 100